from app import db
from app.database.models import Project
from release_tasks import add_tasks
from app.routes.Group import add_groups

db.create_all()

# All Projects which will be added to db. Project name is unique,
# there exists only one of each project
project_TMS = Project(name='TMS', system='TMS', project_responsible='') 
project_Emo_Otto = Project(name='EMO1_Otto', system='Dev_S8_EML', project_responsible='')  
project_6X_FQ = Project(name='6X_FQ', system='Dev_S8_EML', project_responsible='')  
project_DW_Power_Solutions = Project(name='DW_Power_Solutions', system='CEM1_Power_Solutions', project_responsible='vto57o') 
project_AMS2 = Project(name='AMS2', system='CEM1', project_responsible='') 
project_StageV = Project(name='StageV', system='S8_IOM', project_responsible='vto57o') 
project_Scania_Engines_S8 = Project(name='Scania_Engines_S8', system='S8_IOM', project_responsible='vto57o') 
project_Scania_Engines_China4 = Project(name='Scania_Engines_China4', system='S8_IOM', project_responsible='vto57o') 
project_OneTrack = Project(name='Onetrack', system='S7_S8', project_responsible='KKLN2R')
project_Otto_Cem1 = Project(name='Otto_CEM1', system='CEM1', project_responsible='aliin4') 
project_Cbe1_Man = Project(name='CBE1_MAN', system='CEM1', project_responsible='KKLN2R') 
project_V8_Update = Project(name='V8_Update', system='CEM1', project_responsible='') 
project_Np2 = Project(name='NP2', system='CEM1', project_responsible='VBEPZ8') 
project_Dw5 = Project(name='DW5', system='CEM1', project_responsible='mexrq8') 
project_Cbe1_Eu6 = Project(name='CBE1_Eu6', system='CEM1', project_responsible='') 
project_Cbe1_Eu5 = Project(name='CBE1_Eu5', system='CEM1', project_responsible='') 
project_Cbe1 = Project(name='CBE1', system='CEM1', project_responsible='mexrq8') 
project_Lpfc_Mach = Project(name='LPFC_MACH', system='CEM1', project_responsible='aliin4') 
project_AMS1 = Project(name='AMS1', system='EEC_AMS1', project_responsible='') 
project_Scania_Engines_S6IM = Project(name='Scania_Engines_S6IM', system='S6_IOM', project_responsible='') 
project_GSC = Project(name='GSC', system='GSC', project_responsible='') 
project_EEC3 = Project(name='EEC3', system='EEC3', project_responsible='') 
project_Scania_Engines_Defence = Project(name='Scania_Engines_Defence', project_responsible='') 
project_OCS1 = Project(name='OCS1', project_responsible='') 
project_FDC = Project(name='FDC', project_responsible='') 

# add the projects to the database
db.session.add(project_TMS)
db.session.add(project_Emo_Otto)
db.session.add(project_6X_FQ)
db.session.add(project_DW_Power_Solutions)
db.session.add(project_AMS2)
db.session.add(project_StageV)
db.session.add(project_Scania_Engines_S8)
db.session.add(project_Scania_Engines_China4)
db.session.add(project_OneTrack)
db.session.add(project_Otto_Cem1)
db.session.add(project_Cbe1_Man)
db.session.add(project_V8_Update)
db.session.add(project_Np2)
db.session.add(project_Dw5)
db.session.add(project_Cbe1_Eu6)
db.session.add(project_Cbe1_Eu5)
db.session.add(project_Cbe1)
db.session.add(project_Lpfc_Mach)
db.session.add(project_AMS1)
db.session.add(project_Scania_Engines_S6IM)
db.session.add(project_GSC)
db.session.add(project_EEC3)
db.session.add(project_Scania_Engines_Defence)
db.session.add(project_OCS1)
db.session.add(project_FDC)

add_tasks()
add_groups()
db.session.commit()